image: node:17.1-alpine

stages:
  - dependencies
  - lint
  - test
  - build
  - build_docker
  - deploy

.docker_auth: &docker_auth
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    - apk add --no-cache docker-compose

.set_latest_env: &set_latest_env
  - export CRUX_GRPC_AGENT_PORT=$LATEST_CRUX_GRPC_AGENT_PORT
  - export CRUX_GRPC_API_PORT=$LATEST_CRUX_GRPC_API_PORT
  - export CRUX_DOMAIN=$LATEST_CRUX_DOMAIN
  - export CRUX_DOMAIN_ALTS=$LATEST_CRUX_DOMAIN_ALTS
  - export POSTGRES_PASSWORD=$LATEST_POSTGRES_PASSWORD
  - export KRATOS_URL=$LATEST_KRATOS_URL
  - export CRUX_UI_URL=$LATEST_CRUX_UI_URL

cache: &npm_cache
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR-npm
  paths:
    - .npm/
  policy: pull

before_script:
  - npm ci --arch=x64 --platform=linuxmusl --cache .npm --prefer-offline

install_deps:
  stage: dependencies
  cache:
    <<: *npm_cache
    policy: push
  before_script: []
  script:
    - npm ci --arch=x64 --platform=linuxmusl
  only:
    changes:
      - package-lock.json

linter:
  stage: lint
  allow_failure: false
  dependencies:
    - install_deps
  script:
    - npm run lint

unit_tests:
  stage: test
  dependencies:
    - linter
  allow_failure: false
  script:
    - echo 'TBD UNIT TESTS'
  #  - npm run test

e2e_tests:
  stage: test
  dependencies:
    - linter
  allow_failure: false
  script:
    - echo 'TBD E2E TESTS'

build_app:
  stage: build
  allow_failure: false
  dependencies:
    - unit_tests
    - e2e_tests
  script:
    - npx prisma generate
    - npm run build
    - npm prune --production
  artifacts:
    paths:
      - ./node_modules
      - ./dist
    expire_in: 20 minutes

build_image:
  stage: build_docker
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build_app
  only:
    - develop
  allow_failure: false
  cache: []
  <<: *docker_auth
  script:
    - export CRUX_VERSION=$CI_ENVIRONMENT_NAME
    - *set_latest_env
    - docker-compose build
    - docker-compose push
  environment:
    name: latest

build_stable_image:
  stage: build_docker
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build_app
  only:
    - main
  allow_failure: false
  cache: []
  <<: *docker_auth
  script:
    - export CRUX_VERSION=$CI_ENVIRONMENT_NAME
    - docker-compose build
    - docker-compose push crux
  environment:
    name: stable

'Deploy latest to mogyoro':
  image: docker:latest
  services:
  - docker:dind
  stage: deploy
  dependencies:
    - build_image
  only:
    - develop
  when: manual
  allow_failure: false
  tags:
    - crux-latest
  cache: []
  <<: *docker_auth
  script:
    - export CRUX_VERSION=$CI_ENVIRONMENT_NAME
    - *set_latest_env
    - docker-compose pull
    - docker-compose down
    - docker-compose up -d
  environment:
    name: latest
